### ISSUE TITLE
Model Example

### ISSUE THREAD

**Issue by aansubarkah** [shubham715/Cakephp-ArangoDb-Package#1]
Hi, thanks for your great work.
Can you show your your UserTable model? Your library is promising but i can't follow your documentation

**Comment by shubham715** [comment]
Thanks @aansubarkah , I have updated documentation and i am also sharing Model code below . if you face any issue please contact me again .

Model Code
```
<?php
namespace App\Model\Table;

use ArangoDBClient\Connect;

class UsersTable extends \ArangoDBClient\Eloquent\Model
{

}
?>
```

**Comment by aansubarkah** [comment]
awesome, thanks!
